@Kahin.ReportingService_HostAddress = http://localhost:5218

GET {{Kahin.ReportingService_HostAddress}}/health

###

POST {{Kahin.ReportingService_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "TraceId": "edd4e07d-2391-47c1-bf6f-96a96c447585",
  "Title": "Popular Game Sales Reports",
  "Expression": "SELECT * FROM Reports WHERE CategoryId=1 ORDER BY Id Desc"
}

###

POST {{Kahin.ReportingService_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "TraceId": "000-0000",
  "Title": "Popular Game Sales Reports",
  "Expression": "SELECT * FROM Reports WHERE CategoryId=1 ORDER BY Id Desc"
}

###

POST {{Kahin.ReportingService_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "TraceId": "edd4e07d-2391-47c1-bf6f-96a96c447585",
  "Title": "",
  "Expression": "SELECT * FROM Reports WHERE CategoryId=1 ORDER BY Id Desc"
}

###

POST {{Kahin.ReportingService_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "TraceId": "edd4e07d-2391-47c1-bf6f-96a96c447585",
  "Title": "Report Title",
  "Expression": "SELECT * FROM Reports WHERE CategoryId=1 ORDER BY Id Desc"
}

###

POST {{Kahin.ReportingService_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "TraceId": "edd4e07d-2391-47c1-bf6f-96a96c447585",
  "Title": "Popular Game Sales Reports",
  "Expression": ""
}

###

POST {{Kahin.ReportingService_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "TraceId": "edd4e07d-2391-47c1-bf6f-96a96c447585",
  "Title": "Popular Game Sales Reports",
  "Expression": "SELECT * FROM"
}

###

POST {{Kahin.ReportingService_HostAddress}}/getReport
Content-Type: application/json
Accept: application/json

{
  "DocumentId": "1001-23-789e06c8-6b4e-4db9-9db2-9876543210ab"
}

###

POST {{Kahin.ReportingService_HostAddress}}/getReport
Content-Type: application/json
Accept: application/json

{
  "DocumentId": "abc-23-789e06c8-6b4e-4db9-9db2-9876543210ab"
}

###

POST {{Kahin.ReportingService_HostAddress}}/getReport
Content-Type: application/json
Accept: application/json

{
  "DocumentId": "1001-abc-789e06c8-6b4e-4db9-9db2-9876543210ab"
}

###

POST {{Kahin.ReportingService_HostAddress}}/getReport
Content-Type: application/json
Accept: application/json

{
  "DocumentId": "1001-23-8-6b4e-4db9-9db2-9876543210ab"
}

###